export const PermissionStyles = theme => ({
    wrapperPermission: {
        position: 'relative',
        padding: '10px 20px',
    },
    content: {
        display: 'block',
        width: '100%',
        height: 'calc(100vh - 170px)',
        overflow: 'auto',
    },
    moduleHeader: {
        position: 'relative',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'flex-start',
        alignItems: 'center',
        borderBottom: '1px solid',
        borderBottomColor: theme.palette.separator,
        paddingBottom: 10,
    },
    moduleName: {
        alignSelf: 'flex-start',
        textAlign: 'left',
        color: theme.palette.text.primary,
        fontFamily: '"Open Sans", sans-serif',
        fontSize: 22,
        fontWeight: 600,
        margin: '0 0 5px 0',
        boxSizing: 'border-box',
    },
    moduleDescription: {
        alignSelf: 'flex-start',
        color: theme.palette.text.secondary,
        fontFamily: '"Open Sans", sans-serif',
        fontSize: 12,
        fontWeight: 400,
        margin: '0 0 5px 0',
        boxSizing: 'border-box',
    },
    sessionData: {
        position: 'absolute',
        height: 40,
        right: 10,
        top: 0,
        bottom: 0,
        margin: 'auto',
        boxSizing: 'border-box'
    },
    titleSession: {
        alignSelf: 'center',
        color: theme.palette.text.primary,
        fontFamily: '"Open Sans", sans-serif',
        fontSize: 12,
        marginRight: 5,
    },
    typeSession: {
        alignSelf: 'center',
        color: theme.palette.text.secondary,
        fontFamily: '"Open Sans", sans-serif',
        fontSize: 11,
        marginRight: 0,
    },
    appBar: {
        boxShadow: 'none',
        borderBottom: '1px solid',
        borderBottomColor: theme.palette.separator,
    },
    sectionPermission: {
        color: theme.palette.text.secondary,
    },
    currentModule: {
        display: 'inline',
        marginLeft: 5,
        textTransform: 'lowercase',
        fontSize: 15,
        fontWeight: 'normal',
        color: theme.palette.text.secondary,
    }
});